language: ua
discord-webhook-url: "https://discord.com/api/webhooks/1442598222135824495/lBzY48kW9xNxc8IDGKcoe8VWl64bpHqM49XX9PChSe5tjbDE3-EAWe9so6mE8oA_MhPL"
channel-id: 1442598139306709103
# Number of days after which an inactive account requires re-registration
registration_expiry_days: 2
