name: SetupPlug
main: ua.nekit2123.setupplug.Main
version: 0.1.0
api-version: "1.21"
description: "FSMPGAME plugin: Discord webhook join/quit, auth (register/login), tab UI"
authors: [ "nekit2123" ]

softdepend: [Essentials, EssentialsX]

commands:
  register:
    description: Register with a password
    usage: /register <password>
  login:
    description: Login with your password
    usage: /login <password>
  commands:
    description: Show all available plugin commands
    usage: /commands
    tabreload:
      description: Reload tab templates from tab.yml
      usage: /tabreload
  lang:
    description: Change plugin language (en/ua)
    usage: /lang <en|ua>
